# Utiliza la imagen oficial de PostgreSQL 16 como base
FROM postgres:16

# Configuración de variables de entorno predeterminadas
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgrespassword
ENV POSTGRES_DB=postgres

# Expone el puerto estándar de PostgreSQL
EXPOSE 5432